product = input()
price = int(input())
weight = int(input())
money = int(input())

print("Чек")
print(f"{product} - {weight}кг - {price}руб/кг")
print(f"Итого: {weight*price}руб")
print(f"Внесено: {money}руб")
print(f"Сдача: {money-weight*price}руб")